### ISSUE TITLE
Request for GHC 8.2 or 8.4 support

### ISSUE THREAD

**Issue by ilovezfs** [elm-lang/elm-compiler#1695]
Currently Elm compiles with GHC 8.0 in Homebrew. The GHC formulae available in https://github.com/Homebrew/homebrew-core/ are 8.4, 8.2 and 8.0.

Elm is now the only Haskell software in Homebrew/homebrew-core that cannot compile with GHC 8.4 or GHC 8.2. I would like to retire the GHC 8.0 formula as soon as possible but that's not possible until we can build Elm with GHC 8.2 or ideally GHC 8.4.

Thanks for your help.

If I pass `--allow-newer` to `cabal` all of the dependencies build and then the first error is
```
[40 of 87] Compiling Parse.Helpers    ( src/Parse/Helpers.hs, dist/dist-sandbox-641454c9/build/Parse/Helpers.o )

src/Parse/Helpers.hs:61:13: error:
    • Couldn't match type ‘[Char]’
                     with ‘transformers-0.5.2.0:Control.Monad.Trans.Reader.ReaderT
                             Text.Parsec.Indent.Pos
                             Data.Functor.Identity.Identity
                             (SourceM (Either ParseError a) -> Either ParseError a)’
      Expected type: Text.Parsec.Indent.IndentT
                       Data.Functor.Identity.Identity
                       (SourceM (Either ParseError a) -> Either ParseError a)
        Actual type: SourceName
    • In the first argument of ‘runIndent’, namely ‘sourceName’
      In the expression: runIndent sourceName
      In the expression:
        runIndent sourceName $ runParserT aParser table sourceName input
    • Relevant bindings include
        aParser :: IParser a (bound at src/Parse/Helpers.hs:60:34)
        iParseWithTable :: SourceName
                           -> OpTable -> IParser a -> String -> Either ParseError a
          (bound at src/Parse/Helpers.hs:60:1)
   |
61 |   runIndent sourceName $ runParserT aParser table sourceName input
   |             ^^^^^^^^^^

src/Parse/Helpers.hs:215:9: error:
    • Couldn't match type ‘transformers-0.5.2.0:Control.Monad.Trans.Reader.ReaderT
                             Text.Parsec.Indent.Pos m0’
                     with ‘transformers-0.5.2.0:Control.Monad.Trans.State.Lazy.StateT
                             SourcePos Data.Functor.Identity.Identity’
      Expected type: ParsecT String OpTable SourceM ()
        Actual type: Text.Parsec.Indent.IndentParserT
                       String OpTable m0 ()
    • In a stmt of a 'do' block: indented
      In the expression:
        do n <- whitespace
           constraint n <?> Syntax.whitespace
           indented
      In an equation for ‘spacing’:
          spacing
            = do n <- whitespace
                 constraint n <?> Syntax.whitespace
                 indented
    |
215 |         indented
    |         ^^^^^^^^
cabal: Leaving directory '/private/tmp/elm-20180405-2235-mjmnuy/elm-compiler-0.18.0/elm-compiler'
cabal: Error: some packages failed to install:
elm-compiler-0.18-Bsn4azQuNpKBxCbQxBLHa4 failed during the building phase. The
exception was:
ExitFailure 1
elm-make-0.18-EdAAG7jYG0T1gF34nRbUyL depends on elm-make-0.18 which failed to
install.
elm-package-0.18-ElLy9lbk70ZFMP6KAMGGFO depends on elm-package-0.18 which
failed to install.
elm-repl-0.18-CfO4RJPUoASJxV81yVDYp2 depends on elm-repl-0.18 which failed to
install.
```
Full log https://gist.github.com/ilovezfs/6d3b3cf4a8580b1d0f8abc19d3ce701a

**Comment by evancz** [comment]
The master branch builds with 8.2, so when the next version of Elm is released, it will build with more recent stuff. I don't think there is a path to make it happen faster than to keep working on that next release.

**Comment by ilovezfs** [comment]
@evancz awesome. Any rough ETA on next release?

**Comment by evancz** [comment]
I cannot give something really precise. The plan is to have about a month of public beta time once it is ready, so longer than that at least.
